stages:
- name: test
  steps:
  - runScriptConfig:
      image: python:2
      shellScript: |-
        mkdir -p /github.com/opencloudshare/
        ln -s `pwd` /github.com/opencloudshare/Op_portforward
        pip install tornado ConfigParser
        cd /github.com/opencloudshare/Op_portforward
        ls
- name: Publish 
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: 172.30.13.91/sddc/testservice:${CICD_EXECUTION_SEQUENCE}
      