stages:
- name: test
  steps:
  - runScriptConfig:
      image: python:2
      shellScript: |-
        mkdir -p /github.com/opencloudshare/
        ln -s `pwd` /github.com/opencloudshare/Op_portforward
        #pip install tornado ConfigParser
        cd /github.com/opencloudshare/Op_portforward
        ls
        echo "test done"
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: sddc/testservice:${CICD_GIT_COMMIT}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
