stages:
- name: test
  steps:
  - runScriptConfig:
      image: python:2
      shellScript: |-
        mkdir -p /github.com/opencloudshare/
        ln -s `pwd` /github.com/opencloudshare/Op_portforward
        pip install tornado json re time commands ConfigParser
        cd /github.com/opencloudshare/Op_portforward
        ls
timeout: 60
